/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proxy.app;

import org.junit.jupiter.api.Test;


class ProxyDemo {
    @Test void testGetMessage() {
        ProxyDemo ProxyDemo = new ProxyDemo();
        System.out.println("Running test");
    }
}
